### PR TITLE
feat: implement search input

### PR DESCRIPTION
**Pull request by aDogCalledSpot**

### CODE REVIEW

**Review by ctron — APPROVED** [review]
:heart:

**Comment by ctron** [comment]
Btw, if you think it's good enough, feel free to remove the feature flag.

**Comment by aDogCalledSpot** [comment]
> Btw, if you think it's good enough, feel free to remove the feature flag.

I'll try to get it included in other components and once that works well we can remove the feature flag.

**Comment by ctron** [comment]
> > Btw, if you think it's good enough, feel free to remove the feature flag.
> 
> I'll try to get it included in other components and once that works well we can remove the feature flag.

Whenever you think it's ready! No pressure.

**Pull request merged**
